name: ROS
on: [push, pull_request]

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {name: "(noetic)", ROS_DISTRO: noetic, PRERELEASE: true}
          - {name: "(humble)", ROS_DISTRO: humble}
          - {name: "(rolling)", ROS_DISTRO: rolling}
          - {name: "(iron)", ROS_DISTRO: iron}
          - {name: "(noetic, Debug)", ROS_DISTRO: noetic, CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"}
          - {name: "(humble, Debug)", ROS_DISTRO: humble, CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"}
          - {name: "(rolling, Debug)", ROS_DISTRO: rolling, CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"}
          - {name: "(iron, Debug)", ROS_DISTRO: iron, CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"}
    name: ${{ matrix.env.name }}
    env:
      UPSTREAM_WORKSPACE: dependencies.rosinstall
      CTEST_OUTPUT_ON_FAILURE: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
