name: ROS
on: [push, pull_request]

jobs:
  CI:
    strategy:
      matrix:
        env:
          - {name: "(noetic)", ROS_DISTRO: noetic, PRERELEASE: true}
          - {name: "(humble)", ROS_DISTRO: humble}
          - {name: "(rolling)", ROS_DISTRO: rolling}
    name: ${{ matrix.env.name }}
    env:
      UPSTREAM_WORKSPACE: dependencies.rosinstall
      CTEST_OUTPUT_ON_FAILURE: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
