name: ROS-CI
on: [push, pull_request]

jobs:
  CI:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, PRERELEASE: true}
          - {ROS_DISTRO: humble}
          - {ROS_DISTRO: rolling}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
